'use client';

import { useCallback } from 'react';
import type { AmortizationRow } from './HomeLoanAmortization';

type Props = {
  schedule: AmortizationRow[];
  loanAmount: number;
  interestRate: number;
  loanTenure: number;
  monthlyEMI: number;
  totalInterest: number;
  totalAmount: number;
  prepaymentActive?: boolean;
};

const fmt = (n: number) =>
  new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(n);

export default function HomeLoanReportDownload({
  schedule, loanAmount, interestRate, loanTenure, monthlyEMI, totalInterest, totalAmount, prepaymentActive = false,
}: Props) {
  const downloadCSV = useCallback(() => {
    const headers = ['Month', 'Date', 'EMI', 'Principal', 'Interest', ...(prepaymentActive ? ['Prepayment'] : []), 'Balance'];
    const rows = schedule.map((r) => [
      r.month, r.date, Math.round(r.emi), Math.round(r.principal), Math.round(r.interest),
      ...(prepaymentActive ? [Math.round(r.prepayment)] : []), Math.round(Math.max(0, r.balance)),
    ]);
    const summary = [
      ['thinkscope Home Loan Report'], [''],
      ['Loan Amount', loanAmount], ['Interest Rate', `${interestRate}%`],
      ['Tenure', `${loanTenure} years`], ['Monthly EMI', Math.round(monthlyEMI)],
      ['Total Interest', Math.round(totalInterest)], ['Total Payment', Math.round(totalAmount)],
      [''], headers, ...rows,
    ];
    const blob = new Blob([summary.map((r) => r.join(',')).join('\n')], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `thinkscope_HomeLoan_Report_${new Date().toISOString().split('T')[0]}.csv`;
    link.click();
    URL.revokeObjectURL(url);
  }, [schedule, loanAmount, interestRate, loanTenure, monthlyEMI, totalInterest, totalAmount, prepaymentActive]);

  const printReport = useCallback(() => {
    const pw = window.open('', '_blank');
    if (!pw) return;
    const trs = schedule.map((r) =>
      `<tr><td>${r.month}</td><td>${r.date}</td><td style="text-align:right">${fmt(r.emi)}</td><td style="text-align:right">${fmt(r.principal)}</td><td style="text-align:right">${fmt(r.interest)}</td>${prepaymentActive ? `<td style="text-align:right">${r.prepayment > 0 ? fmt(r.prepayment) : '—'}</td>` : ''}<td style="text-align:right">${fmt(Math.max(0, r.balance))}</td></tr>`
    ).join('');
    pw.document.write(`<!DOCTYPE html><html><head><title>thinkscope Home Loan Report</title><style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:system-ui,sans-serif;color:#1f2937;padding:24px;font-size:12px}.h{text-align:center;margin-bottom:24px;padding-bottom:16px;border-bottom:2px solid #10B981}.h h1{font-size:20px;color:#1E7F43}.s{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-bottom:24px}.sc{background:#f9fafb;border:1px solid #e5e7eb;border-radius:8px;padding:12px}.sc .l{font-size:10px;color:#6b7280;text-transform:uppercase;font-weight:600}.sc .v{font-size:16px;font-weight:800;margin-top:4px}table{width:100%;border-collapse:collapse;font-size:11px}th{background:#f3f4f6;padding:8px 6px;text-align:left;font-weight:600;border-bottom:2px solid #e5e7eb}td{padding:6px;border-bottom:1px solid #f3f4f6}tr:nth-child(even){background:#fafafa}.f{margin-top:24px;text-align:center;font-size:10px;color:#9ca3af;border-top:1px solid #e5e7eb;padding-top:12px}@media print{body{padding:12px}}</style></head><body><div class="h"><h1>🏠 thinkscope Home Loan Report</h1><p style="font-size:11px;color:#6b7280">Generated ${new Date().toLocaleDateString('en-IN',{year:'numeric',month:'long',day:'numeric'})}</p></div><div class="s"><div class="sc"><div class="l">Loan Amount</div><div class="v">${fmt(loanAmount)}</div></div><div class="sc"><div class="l">Interest Rate</div><div class="v">${interestRate}% p.a.</div></div><div class="sc"><div class="l">Monthly EMI</div><div class="v" style="color:#1E7F43">${fmt(monthlyEMI)}</div></div><div class="sc"><div class="l">Total Interest</div><div class="v" style="color:#F97316">${fmt(totalInterest)}</div></div></div><h3 style="font-size:14px;margin-bottom:12px">Amortization Schedule (${loanTenure} Years)</h3><table><thead><tr><th>Month</th><th>Date</th><th style="text-align:right">EMI</th><th style="text-align:right">Principal</th><th style="text-align:right">Interest</th>${prepaymentActive?'<th style="text-align:right">Prepayment</th>':''}<th style="text-align:right">Balance</th></tr></thead><tbody>${trs}</tbody></table><div class="f"><p>For educational purposes only. Generated by thinkscope.in</p></div><script>window.print();window.close();</script></body></html>`);
    pw.document.close();
  }, [schedule, loanAmount, interestRate, loanTenure, monthlyEMI, totalInterest, prepaymentActive]);

  return (
    <div className="flex items-center gap-2">
      <button onClick={downloadCSV} className="sip-touch-target flex-1 flex items-center justify-center gap-2 px-4 py-3 min-h-[48px] bg-white border border-gray-200 rounded-xl text-sm font-bold text-gray-700 shadow-sm active:bg-gray-50 transition-all">
        <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}><path strokeLinecap="round" strokeLinejoin="round" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" /></svg>
        Download CSV
      </button>
      <button onClick={printReport} className="sip-touch-target flex-1 flex items-center justify-center gap-2 px-4 py-3 min-h-[48px] bg-primary-600 border border-primary-700 rounded-xl text-sm font-bold text-white shadow-sm active:bg-primary-700 transition-all">
        <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}><path strokeLinecap="round" strokeLinejoin="round" d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z" /></svg>
        Print Report
      </button>
    </div>
  );
}
