// AMC-specific SIP calculator data
// Used by SipAmcContent.tsx for server-side rendered AMC pages

export interface SipAmcData {
  slug: string
  amcName: string
  shortName: string
  aum: string
  founded: string
  topFunds: { name: string; category: string; returns3yr: string }[]
  minSip: string
  uniqueFeature: string
  bestFor: string
  metaTitle: string
  metaDescription: string
  intro: string
}

export const sipAmcData: SipAmcData[] = [
  {
    slug: 'hdfc-sip-calculator',
    amcName: 'HDFC Mutual Fund',
    shortName: 'HDFC',
    aum: '₹7.5 lakh crore',
    founded: '1999',
    minSip: '₹100',
    topFunds: [
      { name: 'HDFC Flexi Cap Fund', category: 'Flexi Cap', returns3yr: '~22%' },
      { name: 'HDFC Mid-Cap Opportunities', category: 'Mid Cap', returns3yr: '~28%' },
      { name: 'HDFC Balanced Advantage', category: 'Dynamic Asset Allocation', returns3yr: '~15%' },
    ],
    uniqueFeature: "India's largest AMC by AUM, strong track record in mid-cap and flexi-cap categories",
    bestFor: 'Long-term wealth creation, investors who want a proven large AMC',
    metaTitle: 'HDFC SIP Calculator 2026 — Top Funds, Min SIP & Returns | gpaisa.in',
    metaDescription: 'Calculate HDFC Mutual Fund SIP returns. HDFC AMC manages ₹7.5L crore AUM. Top funds: HDFC Flexi Cap (~22%), HDFC Mid-Cap (~28%). Min SIP ₹100. Free SIP calculator with amortization.',
    intro: "HDFC Mutual Fund is India's largest asset management company by AUM, managing over ₹7.5 lakh crore across equity, debt, and hybrid funds. Founded in 1999, HDFC AMC has one of the longest performance track records in the Indian mutual fund industry. Its HDFC Flexi Cap Fund and HDFC Mid-Cap Opportunities Fund are consistently among the top performers in their respective categories. For SIP investors, HDFC AMC offers the convenience of investing through HDFC Bank netbanking with same-day allotment for HDFC Bank customers.",
  },
  {
    slug: 'sbi-sip-calculator',
    amcName: 'SBI Mutual Fund',
    shortName: 'SBI',
    aum: '₹10.5 lakh crore',
    founded: '1987',
    minSip: '₹500',
    topFunds: [
      { name: 'SBI Bluechip Fund', category: 'Large Cap', returns3yr: '~16%' },
      { name: 'SBI Magnum Midcap', category: 'Mid Cap', returns3yr: '~25%' },
      { name: 'SBI Contra Fund', category: 'Contra', returns3yr: '~30%' },
    ],
    uniqueFeature: "India's largest AMC overall, government-backed trust, strong distribution network",
    bestFor: 'Conservative investors, government employees, first-time SIP investors',
    metaTitle: 'SBI SIP Calculator 2026 — Top Funds, Min SIP & Returns | gpaisa.in',
    metaDescription: 'Calculate SBI Mutual Fund SIP returns. SBI AMC manages ₹10.5L crore AUM. Top funds: SBI Contra (~30%), SBI Magnum Midcap (~25%). Min SIP ₹500. Free calculator with amortization.',
    intro: "SBI Mutual Fund is India's largest asset management company by total AUM, backed by the State Bank of India — the country's largest public sector bank. This government backing gives SBI Mutual Fund a trust advantage among first-time and conservative investors. The SBI Contra Fund has been one of the standout performers in recent years, while SBI Bluechip offers steady large-cap exposure. SBI AMC has the widest physical distribution network in India, making it accessible even in smaller towns.",
  },
  {
    slug: 'icici-sip-calculator',
    amcName: 'ICICI Prudential Mutual Fund',
    shortName: 'ICICI Pru',
    aum: '₹9.2 lakh crore',
    founded: '1993',
    minSip: '₹100',
    topFunds: [
      { name: 'ICICI Pru Bluechip', category: 'Large Cap', returns3yr: '~17%' },
      { name: 'ICICI Pru Value Discovery', category: 'Value', returns3yr: '~24%' },
      { name: 'ICICI Pru Balanced Advantage', category: 'Dynamic Asset Allocation', returns3yr: '~14%' },
    ],
    uniqueFeature: 'Pioneer of Balanced Advantage Funds in India, strong risk-adjusted return track record',
    bestFor: 'Risk-conscious investors, those wanting automatic equity-debt rebalancing',
    metaTitle: 'ICICI Prudential SIP Calculator 2026 — Top Funds, Min SIP & Returns | gpaisa.in',
    metaDescription: 'Calculate ICICI Prudential SIP returns. ICICI Pru AMC manages ₹9.2L crore AUM. Pioneer of Balanced Advantage Funds. Top funds: Value Discovery (~24%). Min SIP ₹100.',
    intro: 'ICICI Prudential Mutual Fund is a joint venture between ICICI Bank and Prudential Plc (UK), combining Indian banking reach with international fund management expertise. ICICI Pru is widely credited with pioneering the Balanced Advantage Fund category in India — a dynamic asset allocation product that automatically shifts between equity and debt based on market valuations. For SIP investors who want growth but are uncomfortable with pure equity volatility, ICICI Pru\'s Balanced Advantage Fund is one of the most recommended starting points.',
  },
  {
    slug: 'axis-sip-calculator',
    amcName: 'Axis Mutual Fund',
    shortName: 'Axis',
    aum: '₹2.8 lakh crore',
    founded: '2009',
    minSip: '₹100',
    topFunds: [
      { name: 'Axis Flexi Cap Fund', category: 'Flexi Cap', returns3yr: '~16%' },
      { name: 'Axis Midcap Fund', category: 'Mid Cap', returns3yr: '~22%' },
      { name: 'Axis Small Cap Fund', category: 'Small Cap', returns3yr: '~24%' },
    ],
    uniqueFeature: 'Known for quality-focused investment philosophy, strong small and mid cap performance',
    bestFor: 'Growth investors, those comfortable with mid/small cap exposure',
    metaTitle: 'Axis Mutual Fund SIP Calculator 2026 — Top Funds, Min SIP & Returns | gpaisa.in',
    metaDescription: 'Calculate Axis Mutual Fund SIP returns. Axis AMC manages ₹2.8L crore AUM with a quality-focused philosophy. Top funds: Axis Small Cap (~24%), Axis Midcap (~22%). Min SIP ₹100.',
    intro: 'Axis Mutual Fund, the asset management arm of Axis Bank, has built a reputation for a quality-focused investment philosophy — focusing on companies with strong fundamentals and consistent earnings growth rather than pure momentum. Axis Small Cap Fund and Axis Midcap Fund have delivered strong risk-adjusted returns over 5-year periods. Axis AMC offers a seamless SIP experience for Axis Bank account holders with automated debit setup in minutes.',
  },
  {
    slug: 'kotak-sip-calculator',
    amcName: 'Kotak Mahindra Mutual Fund',
    shortName: 'Kotak',
    aum: '₹4.2 lakh crore',
    founded: '1998',
    minSip: '₹100',
    topFunds: [
      { name: 'Kotak Flexicap Fund', category: 'Flexi Cap', returns3yr: '~17%' },
      { name: 'Kotak Emerging Equity', category: 'Mid Cap', returns3yr: '~26%' },
      { name: 'Kotak Small Cap Fund', category: 'Small Cap', returns3yr: '~23%' },
    ],
    uniqueFeature: 'Strong mid-cap focus, consistent fund manager team, good long-term track record',
    bestFor: 'Mid-cap focused investors, long-term systematic investors',
    metaTitle: 'Kotak Mutual Fund SIP Calculator 2026 — Top Funds, Min SIP & Returns | gpaisa.in',
    metaDescription: 'Calculate Kotak Mahindra SIP returns. Kotak AMC manages ₹4.2L crore AUM with 25+ years history. Top funds: Kotak Emerging Equity (~26%). Min SIP ₹100. Free SIP calculator.',
    intro: 'Kotak Mahindra Mutual Fund has maintained a consistent investment team and philosophy over its 25+ year history, which is reflected in long-term performance across categories. Kotak Emerging Equity Fund is one of the most recommended mid-cap SIP choices for investors with a 7–10 year horizon. Kotak AMC\'s fund management team has seen relatively low attrition compared to peers — fund manager continuity is an underrated factor in SIP planning.',
  },
  {
    slug: 'lic-sip-calculator',
    amcName: 'LIC Mutual Fund',
    shortName: 'LIC',
    aum: '₹35,000 crore',
    founded: '1989',
    minSip: '₹1,000',
    topFunds: [
      { name: 'LIC MF Large & Mid Cap', category: 'Large & Mid Cap', returns3yr: '~19%' },
      { name: 'LIC MF Flexi Cap', category: 'Flexi Cap', returns3yr: '~15%' },
      { name: 'LIC MF Infrastructure', category: 'Sectoral', returns3yr: '~28%' },
    ],
    uniqueFeature: 'Government-backed trust, strong agent distribution, accessible in rural areas',
    bestFor: 'LIC policyholders, conservative investors, rural/semi-urban investors',
    metaTitle: 'LIC Mutual Fund SIP Calculator 2026 — Top Funds, Min SIP & Returns | gpaisa.in',
    metaDescription: 'Calculate LIC Mutual Fund SIP returns. Government-backed AMC with ₹35,000 crore AUM. Top funds: LIC MF Infrastructure (~28%). Min SIP ₹1,000. Wide rural reach.',
    intro: 'LIC Mutual Fund, backed by Life Insurance Corporation of India, carries the same government-backed trust that has made LIC one of India\'s most recognized financial brands for over 60 years. While LIC AMC is smaller than private sector peers, it offers a range of equity and debt funds with a minimum SIP of ₹1,000. LIC AMC\'s agent distribution network gives it strong reach in semi-urban and rural areas where private AMCs have limited physical presence.',
  },
  {
    slug: 'nippon-sip-calculator',
    amcName: 'Nippon India Mutual Fund',
    shortName: 'Nippon India',
    aum: '₹5.1 lakh crore',
    founded: '1995',
    minSip: '₹100',
    topFunds: [
      { name: 'Nippon India Small Cap', category: 'Small Cap', returns3yr: '~35%' },
      { name: 'Nippon India Growth Fund', category: 'Mid Cap', returns3yr: '~27%' },
      { name: 'Nippon India Multi Cap', category: 'Multi Cap', returns3yr: '~22%' },
    ],
    uniqueFeature: "India's largest small-cap fund by AUM, strong retail investor focus",
    bestFor: 'Small-cap focused investors, long-term high-growth seekers',
    metaTitle: 'Nippon India SIP Calculator 2026 — Top Funds, Min SIP & Returns | gpaisa.in',
    metaDescription: "Calculate Nippon India Mutual Fund SIP returns. India's largest small-cap fund. Nippon India Small Cap (~35% 3yr). ₹5.1L crore AUM. Min SIP ₹100. Free calculator.",
    intro: "Nippon India Mutual Fund (formerly Reliance Mutual Fund) manages India's largest small-cap fund by AUM — Nippon India Small Cap Fund — which has been a standout performer over 5 and 10-year periods. Nippon India AMC has one of the widest retail investor bases in India and a strong focus on digital accessibility. For SIP investors specifically targeting small-cap exposure for long-term wealth creation, Nippon India is the natural starting point given the scale and track record of its small-cap franchise.",
  },
  {
    slug: 'aditya-birla-sip-calculator',
    amcName: 'Aditya Birla Sun Life Mutual Fund',
    shortName: 'ABSL',
    aum: '₹3.8 lakh crore',
    founded: '1994',
    minSip: '₹100',
    topFunds: [
      { name: 'ABSL Flexi Cap', category: 'Flexi Cap', returns3yr: '~18%' },
      { name: 'ABSL Frontline Equity', category: 'Large Cap', returns3yr: '~15%' },
      { name: 'ABSL Small Cap', category: 'Small Cap', returns3yr: '~22%' },
    ],
    uniqueFeature: 'Strong debt fund franchise, balanced equity-debt offering, good large-cap track record',
    bestFor: 'Investors wanting both equity and debt SIP options from one AMC',
    metaTitle: 'Aditya Birla Sun Life SIP Calculator 2026 — Top Funds, Min SIP & Returns | gpaisa.in',
    metaDescription: 'Calculate ABSL Mutual Fund SIP returns. Aditya Birla Sun Life AMC manages ₹3.8L crore AUM. Strong in debt and equity. ABSL Flexi Cap (~18%). Min SIP ₹100.',
    intro: 'Aditya Birla Sun Life Mutual Fund is part of the Aditya Birla Group, one of India\'s largest conglomerates, with a joint venture with Sun Life Financial (Canada). ABSL AMC has built particular strength in debt and liquid fund categories alongside its equity offering — making it a good choice for investors who want to manage both their equity SIP and liquid fund parking at the same AMC. The ABSL Frontline Equity Fund is a long-standing large-cap option with a 25+ year track record.',
  },
  {
    slug: 'idfc-sip-calculator',
    amcName: 'IDFC First Mutual Fund',
    shortName: 'IDFC',
    aum: '₹1.8 lakh crore',
    founded: '2000',
    minSip: '₹100',
    topFunds: [
      { name: 'IDFC Flexi Cap', category: 'Flexi Cap', returns3yr: '~17%' },
      { name: 'IDFC Sterling Value', category: 'Value', returns3yr: '~25%' },
      { name: 'IDFC Tax Advantage ELSS', category: 'ELSS', returns3yr: '~20%' },
    ],
    uniqueFeature: 'Strong value-investing philosophy, good ELSS offering for tax saving',
    bestFor: 'Value investors, tax-saving SIP (ELSS) investors',
    metaTitle: 'IDFC Mutual Fund SIP Calculator 2026 — Top Funds, Min SIP & Returns | gpaisa.in',
    metaDescription: 'Calculate IDFC First Mutual Fund SIP returns. Strong value-investing philosophy. IDFC Sterling Value (~25%), Tax Advantage ELSS (~20%). ₹1.8L crore AUM. Min SIP ₹100.',
    intro: 'IDFC Mutual Fund, now part of the IDFC First Bank group, follows a value-oriented investment philosophy across most of its equity funds. The IDFC Sterling Value Fund has been a consistent performer for investors comfortable with a contrarian investment approach. For investors looking for a tax-saving SIP under Section 80C, IDFC\'s Tax Advantage ELSS Fund offers a 3-year lock-in SIP option that qualifies for tax deduction up to ₹1.5 lakh per year.',
  },
  {
    slug: 'dsp-sip-calculator',
    amcName: 'DSP Mutual Fund',
    shortName: 'DSP',
    aum: '₹1.6 lakh crore',
    founded: '1996',
    minSip: '₹100',
    topFunds: [
      { name: 'DSP Flexi Cap', category: 'Flexi Cap', returns3yr: '~19%' },
      { name: 'DSP Midcap Fund', category: 'Mid Cap', returns3yr: '~24%' },
      { name: 'DSP Small Cap', category: 'Small Cap', returns3yr: '~26%' },
    ],
    uniqueFeature: 'Independent AMC (not bank-backed), strong research team, consistent mid-cap performance',
    bestFor: 'Investors who prefer AMC independence, mid-cap focused SIP',
    metaTitle: 'DSP Mutual Fund SIP Calculator 2026 — Top Funds, Min SIP & Returns | gpaisa.in',
    metaDescription: 'Calculate DSP Mutual Fund SIP returns. Independent AMC with strong research. DSP Midcap (~24%), DSP Small Cap (~26%). ₹1.6L crore AUM. Min SIP ₹100. Free SIP calculator.',
    intro: "DSP Mutual Fund is one of India's few truly independent AMCs — not backed by any bank or conglomerate. This independence is seen as an advantage by some investors as it reduces potential conflicts of interest in fund management. DSP has a strong in-house research team and has delivered consistent performance in mid-cap and small-cap categories. The DSP Midcap Fund is one of the most recommended systematic investment options for investors with a 7+ year horizon.",
  },
  {
    slug: 'franklin-templeton-sip-calculator',
    amcName: 'Franklin Templeton India',
    shortName: 'Franklin Templeton',
    aum: '₹1.2 lakh crore',
    founded: '1996',
    minSip: '₹500',
    topFunds: [
      { name: 'Franklin India Flexi Cap', category: 'Flexi Cap', returns3yr: '~20%' },
      { name: 'Franklin India Prima', category: 'Mid Cap', returns3yr: '~23%' },
      { name: 'Franklin India Smaller Companies', category: 'Small Cap', returns3yr: '~28%' },
    ],
    uniqueFeature: 'Global AMC with Indian operations, strong small-cap track record, value-oriented',
    bestFor: 'Investors comfortable with global AMC, long-term small/mid cap SIP',
    metaTitle: 'Franklin Templeton SIP Calculator 2026 — Top Funds, Min SIP & Returns | gpaisa.in',
    metaDescription: 'Calculate Franklin Templeton India SIP returns. Global AMC, 75+ years experience. Franklin India Smaller Companies (~28%). ₹1.2L crore AUM. Min SIP ₹500.',
    intro: 'Franklin Templeton is one of the world\'s largest asset managers with over 75 years of global experience, bringing international investment research capabilities to Indian markets. After the 2020 debt fund episode, Franklin Templeton India has refocused strongly on equity funds where its track record remains solid — particularly in the small and mid-cap space. Franklin India Smaller Companies Fund has been a standout multi-year performer. Minimum SIP starts at ₹500.',
  },
  {
    slug: 'tata-sip-calculator',
    amcName: 'Tata Mutual Fund',
    shortName: 'Tata',
    aum: '₹1.5 lakh crore',
    founded: '1994',
    minSip: '₹150',
    topFunds: [
      { name: 'Tata Small Cap Fund', category: 'Small Cap', returns3yr: '~27%' },
      { name: 'Tata Flexi Cap', category: 'Flexi Cap', returns3yr: '~18%' },
      { name: 'Tata Digital India', category: 'Sectoral', returns3yr: '~15%' },
    ],
    uniqueFeature: 'Part of the Tata Group — one of India\'s most trusted business houses',
    bestFor: 'Brand-conscious investors, small-cap focused SIP',
    metaTitle: 'Tata Mutual Fund SIP Calculator 2026 — Top Funds, Min SIP & Returns | gpaisa.in',
    metaDescription: 'Calculate Tata Mutual Fund SIP returns. Part of Tata Group, ₹1.5L crore AUM. Tata Small Cap Fund (~27%). Min SIP ₹150. Free SIP calculator with year-wise breakdown.',
    intro: 'Tata Mutual Fund carries the brand trust of the Tata Group — one of India\'s oldest and most respected conglomerates. Tata AMC has seen significant improvement in performance and AUM growth in recent years, with Tata Small Cap Fund emerging as one of the consistent performers in the small-cap category. For investors who value the Tata brand\'s reputation for integrity and corporate governance, Tata Mutual Fund offers a range of equity SIP options with a minimum SIP of ₹150.',
  },
  {
    slug: 'utm-sip-calculator',
    amcName: 'UTI Mutual Fund',
    shortName: 'UTI',
    aum: '₹3.2 lakh crore',
    founded: '1964',
    minSip: '₹500',
    topFunds: [
      { name: 'UTI Flexi Cap', category: 'Flexi Cap', returns3yr: '~16%' },
      { name: 'UTI Mid Cap', category: 'Mid Cap', returns3yr: '~22%' },
      { name: 'UTI NIFTY 50 Index', category: 'Index', returns3yr: '~13%' },
    ],
    uniqueFeature: "India's oldest AMC (60+ years), strong index fund offering, government heritage",
    bestFor: 'Conservative investors, index fund SIP investors',
    metaTitle: 'UTI Mutual Fund SIP Calculator 2026 — Top Funds, Min SIP & Returns | gpaisa.in',
    metaDescription: "Calculate UTI Mutual Fund SIP returns. India's oldest AMC, est. 1964. ₹3.2L crore AUM. UTI Nifty 50 Index Fund for low-cost SIP. Min SIP ₹500. Free calculator.",
    intro: "UTI Mutual Fund holds the distinction of being India's oldest asset management company, established in 1964 — over a decade before most of its current competitors. With 60+ years of operation, UTI has navigated multiple market cycles and remains one of India's most trusted AMC names among older investors. UTI has also built a strong passive investing franchise — its UTI Nifty 50 Index Fund is one of the most recommended low-cost index SIP options for investors who prefer market-linked returns without active management risk.",
  },
  {
    slug: 'motilal-oswal-sip-calculator',
    amcName: 'Motilal Oswal Mutual Fund',
    shortName: 'Motilal Oswal',
    aum: '₹1.1 lakh crore',
    founded: '2009',
    minSip: '₹500',
    topFunds: [
      { name: 'Motilal Oswal Midcap Fund', category: 'Mid Cap', returns3yr: '~38%' },
      { name: 'Motilal Oswal Flexicap', category: 'Flexi Cap', returns3yr: '~22%' },
      { name: 'Motilal Oswal NASDAQ 100 FOF', category: 'International', returns3yr: '~12%' },
    ],
    uniqueFeature: 'Focus investing philosophy (concentrated portfolio), top-performing mid-cap fund, international fund access',
    bestFor: 'High-conviction investors, US market exposure seekers, mid-cap SIP',
    metaTitle: 'Motilal Oswal SIP Calculator 2026 — Top Funds, Min SIP & Returns | gpaisa.in',
    metaDescription: "Calculate Motilal Oswal Mutual Fund SIP returns. Focus investing philosophy. Motilal Oswal Midcap (~38% 3yr). NASDAQ 100 FOF for US exposure. ₹1.1L crore AUM. Min SIP ₹500.",
    intro: 'Motilal Oswal Mutual Fund follows a distinctive "focus investing" philosophy — holding concentrated portfolios of high-conviction stocks rather than diversified holdings. This approach has produced exceptional results in the mid-cap category: Motilal Oswal Midcap Fund has been among India\'s best-performing mid-cap funds with a 3-year return above 35%. For investors who want international diversification through SIP, Motilal Oswal\'s NASDAQ 100 Fund of Fund offers exposure to US technology companies in Indian rupees.',
  },
  {
    slug: 'mirae-asset-sip-calculator',
    amcName: 'Mirae Asset Mutual Fund',
    shortName: 'Mirae Asset',
    aum: '₹2.2 lakh crore',
    founded: '2008',
    minSip: '₹99',
    topFunds: [
      { name: 'Mirae Asset Large Cap', category: 'Large Cap', returns3yr: '~16%' },
      { name: 'Mirae Asset Emerging Bluechip', category: 'Large & Mid Cap', returns3yr: '~21%' },
      { name: 'Mirae Asset Tax Saver', category: 'ELSS', returns3yr: '~18%' },
    ],
    uniqueFeature: 'Korean-backed AMC with strong large-cap and ELSS track record, lowest min SIP at ₹99',
    bestFor: 'Large-cap investors, ELSS tax-saving SIP investors, beginners (low min SIP)',
    metaTitle: 'Mirae Asset SIP Calculator 2026 — Top Funds, Min SIP & Returns | gpaisa.in',
    metaDescription: 'Calculate Mirae Asset Mutual Fund SIP returns. Lowest min SIP ₹99. Strong large-cap track record. Mirae Asset Emerging Bluechip (~21%). ₹2.2L crore AUM. ELSS tax-saving SIP.',
    intro: 'Mirae Asset is a South Korean asset management group that entered India in 2008 and has since built one of the strongest track records in the Indian large-cap and large-mid cap categories. Mirae Asset Emerging Bluechip Fund is consistently recommended as a top SIP choice for investors wanting exposure across large and mid-cap segments. With a minimum SIP of just ₹99 — the lowest among major AMCs — Mirae Asset is particularly accessible for first-time SIP investors starting small.',
  },
]

// Per-AMC honest caveats for the "Is X right for you?" section
export const amcCaveats: Record<string, string> = {
  'hdfc-sip-calculator': "HDFC AMC's larger fund range means more choice, but also more complexity in selection — stick to its flagship funds for simplicity.",
  'sbi-sip-calculator': 'SBI AMC has a smaller range of consistently top-performing equity funds compared to some private-sector peers — focus on established flagship funds.',
  'icici-sip-calculator': "ICICI Pru's fund range is large — some niche funds have underperformed. Focus on its flagship equity and balanced advantage offerings.",
  'axis-sip-calculator': "Axis AMC's recent performance in some flagship funds has been inconsistent after a period of exceptional returns — evaluate 5-year data carefully.",
  'kotak-sip-calculator': 'Kotak AMC is strong in mid-cap but has fewer standout options in the large-cap category compared to SBI or ICICI Pru.',
  'lic-sip-calculator': 'LIC AMC has a smaller fund range than private-sector peers and a minimum SIP of ₹1,000 — not ideal for those wanting to start with very small amounts.',
  'nippon-sip-calculator': "Nippon India's small-cap fund carries higher volatility — suitable only for investors with a 7+ year horizon who can stomach short-term drawdowns.",
  'aditya-birla-sip-calculator': 'ABSL AMC has faced some fund manager turnover in equity funds in recent years — verify the current manager and their track record before investing.',
  'idfc-sip-calculator': "IDFC's AUM is smaller than the top-5 AMCs, which may limit product breadth — but its core value-oriented funds have a solid long-term record.",
  'dsp-sip-calculator': "DSP's independence is a strength, but its smaller distribution network means fewer physical touchpoints if you prefer in-person advisory.",
  'franklin-templeton-sip-calculator': 'Franklin Templeton India carried reputational risk after the 2020 debt fund closure episode — equity fund track record remains intact, but verify comfort with the brand.',
  'tata-sip-calculator': "Tata AMC has fewer top-performing funds across all categories compared to HDFC or SBI — its strength is concentrated in small-cap and select sectoral funds.",
  'utm-sip-calculator': "UTI's actively managed equity funds have not always matched top private-sector peers on returns — its strongest value proposition remains the low-cost index fund range.",
  'motilal-oswal-sip-calculator': "Motilal Oswal's focus investing means higher concentration risk — its funds can significantly underperform in broad market downturns affecting specific sectors.",
  'mirae-asset-sip-calculator': "Mirae Asset temporarily closed some funds to new SIP investors due to AUM caps in the past — verify current availability before starting a new SIP.",
}

export function getSipAmcDataBySlug(slug: string): SipAmcData | undefined {
  return sipAmcData.find((d) => d.slug === slug)
}
